### PR TITLE
Add support for newlines in comment blocks

### PR DESCRIPTION
**Pull request by cryptomilk**

### CODE REVIEW

**Comment by cryptomilk** [comment]
```lua
require('commented').setup {
    keybindings = {
        n = "gc",
        v = "gc",
        nl = "gcc"
    },
    custom_cms = {
        c = {
            prefer_block_comment = true,
            insert_newlines = true,
            block = '#if 0%s#endif',
        }
    }
}
```

**Comment by winston0410** [comment]
Thanks nice work! Although this does work, `custom_cms` is initially used for denoting custom `commentstring` for a specific language. I think it may be better if it is structured like this:

```lua
require('commented').setup {
    keybindings = {
        n = "gc",
        v = "gc",
        nl = "gcc"
    },
    lang_options = {
        c = {
            prefer_block_comment = true,
            insert_newlines = true,
            cms = {
               block = '#if 0%s#endif',
            }
        }
    }
}
```

**Comment by cryptomilk** [comment]
I'm not sure I fully understand. So what should happen to `custom_cms`, remove it?

**Comment by winston0410** [comment]
Um I think so, `custom_cms` should be nested inside `lang_options` I guess, as it is language specific

So the `cms` inside `lang_options` should do what `custom_cms` should do, yet taking `inline` and `block` directly.

**Comment by cryptomilk** [comment]
Here we go :-)

**Comment by winston0410** [comment]
@cryptomilk Nice work! thank you

**Pull request merged**
